### ISSUE TITLE
Failed to resolve scalafmt version, maybe related to proxy issues

### ISSUE THREAD

**Issue by pedrohjordao** [SimonJPegg/mvn_scalafmt#49]
**Describe the bug**
Hello,
In a corporate environment the plugin gives out the error 

`[ERROR]
org.scalafmt.dynamic.exceptions.ScalafmtException: failed to resolve Scalafmt version ‘2.0.0`

This only happens for some people that have in common being behind a proxy, this also happens in our jenkins pipeline that is also behind a proxy. 

Version 1.0.1 of the plugin gives out the error a few times but then it seems to be able to validate 

Version 1.0.2 only shows the error once and is able to validate

**Environment :**
    - OS: Linux (both native and docker), Windows and Mac
    - maven version 3.6.2
    - scalafmt version 2.0.0 
    - Version 1.0.1 and 1.0.2

**Comment by SimonJPegg** [comment]
Could you confirm if those users have set the proxy details correctly in their `settings.xml`?  Are they able to download scalafmt without the plugin (i.e. adding it directly to their pom)?

**Comment by pedrohjordao** [comment]
Sorry about the delay, somehow I missed your comment

Yes, in principle they are able to download it.

I just noticed something that might be strange though, it seems like it's trying to download the version for scala 2.12 even though it is configured for 2.11
Besides, running locally I don't see the logs for downloading the cli version of scalafmt

here are the logs on our jenkins

```
[INFO] Building library-sa-checker 3.2.1-SNAPSHOT

[INFO] --------------------------------[ jar ]---------------------------------

[INFO] 

[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ library-sa-checker ---

[INFO] 

[INFO] --- mvn-scalafmt_2.11:1.0.1:format (default) @ library-sa-checker ---

Downloading https://repo1.maven.org/maven2/org/scalameta/scalafmt-cli_2.12/2.0.0/scalafmt-cli_2.12-2.0.0.pom

Downloading https://repo1.maven.org/maven2/org/scalameta/scalafmt-cli_2.12/2.0.0/scalafmt-cli_2.12-2.0.0.pom.sha1

Downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.12/scala-reflect-2.11.12.pom.sha1

Downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.12/scala-reflect-2.11.12.pom

Downloading https://oss.sonatype.org/content/repositories/releases/org/scala-lang/scala-reflect/2.11.12/scala-reflect-2.11.12.pom.sha1

Downloading https://oss.sonatype.org/content/repositories/releases/org/scala-lang/scala-reflect/2.11.12/scala-reflect-2.11.12.pom

Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/scalafmt-cli_2.12/2.0.0/scalafmt-cli_2.12-2.0.0.pom.sha1

Downloading https://oss.sonatype.org/content/repositories/releases/org/scalameta/scalafmt-cli_2.12/2.0.0/scalafmt-cli_2.12-2.0.0.pom

Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scala-reflect/2.11.12/scala-reflect-2.11.12.pom

Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scala-reflect/2.11.12/scala-reflect-2.11.12.pom.sha1

Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/scalafmt-cli_2.12/2.0.0/scalafmt-cli_2.12-2.0.0.pom.sha1

Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/scalafmt-cli_2.12/2.0.0/scalafmt-cli_2.12-2.0.0.pom

[ERROR] ScalaFmt: error: /home/cloud/jenkins_slave/workspace/TIBRANCH_feature_boom-stick-N7PWERIP5N672GJZFYDGZIJTCQTMHKPT7TSOXNWBOPLEFBYARSZQ/.scalafmt.conf: failed to resolve Scalafmt version '2.0.0'

[ERROR] ScalaFmt: error: /home/cloud/jenkins_slave/workspace/TIBRANCH_feature_boom-stick-N7PWERIP5N672GJZFYDGZIJTCQTMHKPT7TSOXNWBOPLEFBYARSZQ/.scalafmt.conf: failed to resolve Scalafmt version '2.0.0'

[ERROR] ScalaFmt: error: /home/cloud/jenkins_slave/workspace/TIBRANCH_feature_boom-stick-N7PWERIP5N672GJZFYDGZIJTCQTMHKPT7TSOXNWBOPLEFBYARSZQ/.scalafmt.conf: failed to resolve Scalafmt version '2.0.0'

[ERROR] ScalaFmt: error: /home/cloud/jenkins_slave/workspace/TIBRANCH_feature_boom-stick-N7PWERIP5N672GJZFYDGZIJTCQTMHKPT7TSOXNWBOPLEFBYARSZQ/.scalafmt.conf: failed to resolve Scalafmt version '2.0.0'

[ERROR] ScalaFmt: error: /home/cloud/jenkins_slave/workspace/TIBRANCH_feature_boom-stick-N7PWERIP5N672GJZFYDGZIJTCQTMHKPT7TSOXNWBOPLEFBYARSZQ/.scalafmt.conf: failed to resolve Scalafmt version '2.0.0'

[ERROR] ScalaFmt: error: /home/cloud/jenkins_slave/workspace/TIBRANCH_feature_boom-stick-N7PWERIP5N672GJZFYDGZIJTCQTMHKPT7TSOXNWBOPLEFBYARSZQ/.scalafmt.conf: failed to resolve Scalafmt version '2.0.0'
```

**Comment by antonoal** [comment]
Hi
I've got the same problem. 
In my case however there's no proxy but a corporate mirror of Maven. All the repos are set up correctly in settings.xml but then it fails to resolve scalafmt (v2.3.2 in my case) cause I believe it ignores repository settings and tries going online.

**Comment by pedrohjordao** [comment]
> Hi
> I've got the same problem.
> In my case however there's no proxy but a corporate mirror of Maven. All the repos are set up correctly in settings.xml but then it fails to resolve scalafmt (v2.3.2 in my case) cause I believe it ignores repository settings and tries going online.

Yes, that seems like the same issue since we also use a mirror

**Comment by SimonJPegg** [comment]
Looks like this is a bug on Scalafmt: https://github.com/scalameta/scalafmt/issues/1521. 
I've pushed a [1.0.4-RC1](https://github.com/SimonJPegg/mvn_scalafmt/tree/feature/1.0.4-RC1) version, can you give that a try to see if it works for you.

**Comment by pedrohjordao** [comment]
I'm still getting the same error but the build fails

Before it would indicate the error but the build would be successful (though we eventually noticed it didn't validate the formatting at all, different from what I've mentioned in the original issue)

**Comment by pedrohjordao** [comment]
Another coworker (the one running behind a proxy) is getting the following error 

Failed to execute goal org.antipathy:mvn-scalafmt_2.11:1.0.4-RC1:format (default) on project library-sa-checker: Execution default of goal org.antipathy:mvn-scalafmt_2.11:1.0.4-RC1:format failed: An API incompatibility was encountered while executing org.antipathy:mvn-scalafmt_2.11:1.0.4-RC1:format: java.lang.IncompatibleClassChangeError: Method ‘org.scalafmt.interfaces.Scalafmt org.scalafmt.interfaces.Scalafmt.create(java.lang.ClassLoader)’ must be InterfaceMethodref constant
[ERROR] —————————————————–

**Comment by tashoyan** [comment]
I also get this error:
```text
org.scalafmt.dynamic.exceptions.ScalafmtException: failed to resolve Scalafmt version '2.4.2'
```
Version of mvn-scalafmt_2.12: 1.0.3
I tried to set various Scalafmt versions in the .scalafmt.conf file, but no success.

Just a guess: the problem is caused by non-standard way of getting Scalafmt into the classpath of the plugin. AFAIK, it uses URLClassLoader to download Scalafmt from internet, but this does not work in a corporate network with an internal Nexus or Artifactory.

The standard way is to declare a [dependency for the plugin](https://maven.apache.org/pom.html#Plugins) itself:

```xml
<plugin>
  <groupId>org.antipathy</groupId>
  <artifactId>mvn-scalafmt_2.12</artifactId>
  <version>1.0.3</version>
  <configuration>
    ...
  </configuration>
  <dependencies>
     <dependency>
        <groupId>org.scalameta</groupId>
        <artifactId>scalafmt-dynamic_2.12</artifactId>
        <version>2.4.2</version>
      </dependency>
      <dependency>
        <groupId>org.scalameta</groupId>
        <artifactId>scalafmt-interfaces</artifactId>
        <version>2.4.2</version>
      </dependency>
      <dependency>
        <groupId>org.scalameta</groupId>
        <artifactId>scalafmt-core_2.12</artifactId>
        <version>2.4.2</version>
      </dependency>
      ... whatever else is needed ...
    </dependencies>
</plugin>
```
I tried it but still got the same error.

**Comment by NoamShaish** [comment]
One possiable solution would be to use ```withMavenRepositories``` on Scalafmt builder.
This way user can direct scalafmt dynamic to enterprise repositories behind the same proxy.
In my case it will solve the issue since we are mirroring maven central into our own maven repository.

**Comment by SimonJPegg** [comment]
@pedrohjordao  tried that one with version [1.0.4-RC1](https://github.com/SimonJPegg/mvn_scalafmt/tree/feature/1.0.4-RC1), but it doesn't appear to have resolved the issue for @pedrohjordao.  This isn't one that I'm able to replicate.

**Comment by NoamShaish** [comment]
@SimonJPegg @pedrohjordao does the maven project is pointing to a corporate maven-repository?
BTW the changes were not yet introduced in the 1.0.4-RC1 on maven central, can this RC be published again please

**Comment by NoamShaish** [comment]
@SimonJPegg Any update when a new RC will be available?

**Comment by NoamShaish** [comment]
@SimonJPegg ping

**Comment by NoamShaish** [comment]
@SimonJPegg Can you please create a new RC

**Comment by SimonJPegg** [comment]
> @SimonJPegg Can you please create a new RC

Done, RC-2 should be available in central in a couple of hours.  (I'm waiting for https://github.com/SimonJPegg/mvn_scalafmt/pull/51 before the next release BTW).

**Comment by NoamShaish** [comment]
@SimonJPegg Great!!! Thanks.
@pedrohjordao could you please try the new RC if its helps with your issue please.

**Comment by NoamShaish** [comment]
@SimonJPegg Just noticed you created only Scala 2.13 RC2. could you please create also 2.11 RC2.

**Comment by NoamShaish** [comment]
@SimonJPegg Can you please create a new Scala 2.11 RC

**Comment by SimonJPegg** [comment]
@NoamShaish I'm not planning to release another 2.11 version.  Judging by [56](https://github.com/SimonJPegg/mvn_scalafmt/issues/56), there are issues with that version on later JVM versions.

**Comment by NoamShaish** [comment]
@SimonJPegg until Spark is moving away from Scala 2.11 there are alot of 2.11 users (like me) that are using this plugin. 
I would really appreciate if you can at least create a RC for 2.11 so I can use the fix I introduced.

**Comment by SimonJPegg** [comment]
Done, I've added github actions to the repo, so commits to master will automatically trigger new releases.  Note the version number change (in the readme) you'll want release [2.11-1.0.1589315803.45268b1](https://github.com/SimonJPegg/mvn_scalafmt/releases/tag/2.11-1.0.1589315803.45268b1)

**Comment by NoamShaish** [comment]
@SimonJPegg Thank you very much.

**Comment by SimonJPegg** [comment]
@antonoal are you still seeing this issue with the most recent release?

**Comment by antonoal** [comment]
It’s irrelevant for me now as we’ve moved the project to sbt

**Comment by nickhudkins** [comment]
Perhaps the README could be updated so that this is clearer. I fought for way too long trying to understand what `1.0something` was intended to represent and the `${scala.binary.version}` seemed to confuse the issue more. I'll open a PR and see what ya'll think. Thanks for your work on this project. Once I got past that issue, it worked!

**Comment by pedrohjordao** [comment]
I haven't had time to look into this for a while.

I'll experiment with the patch and get back to you today.

edit: the `1.0.1589315803.45268b1` version requires maven version 3.6.3, while our CICD pipeline is stuck with version 3.6.0.

Would it be possible to roll back to a lower requirement? If not, as soon as we get an updated maven i'll try again.

**Comment by SimonJPegg** [comment]
I've reverted to maven 3.6.0 as of version `1.0.1594457227.9c01d4f` if you want to give it a try now

**Comment by pedrohjordao** [comment]
Sadly still having issues on jenkins: 

```
[ERROR] Failed to execute goal org.antipathy:mvn-scalafmt_2.11:1.0.1594457227.9c01d4f:format (default-cli) on project library-sa-checker: Error formatting Scala files: failed to resolve Scalafmt version '2.6.2' -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Runs fine locally,though

**Comment by SimonJPegg** [comment]
@pedrohjordao is  `<useSpecifiedRepositories>true</useSpecifiedRepositories> ` set and the 2.6.2 version of scalafmt exists in the mirroring repo?

**Comment by pedrohjordao** [comment]
Yup, missed that
Works perfectly now!

**Comment by SimonJPegg** [comment]
@pedrohjordao thanks, closing this ticket.
